export const PLAYER_JOINED = "PLAYER_JOINED";
export const UPDATE_PLAYER_SNAKE = "UPDATE_PLAYER_SNAKE";
export const CLEANUP_STALLED_PLAYERS = "CLEANUP_STALLED_PLAYERS";
export const SPAWN_FOOD = "SPAWN_FOOD";
export const INCREASE_SCORE = "INCREASE_SCORE";
export const INCREASE_SPEED = "INCREASE_SPEED";
